id: inscript
name: Inscription Tools Store
description: A collection of Bitcoin inscription tools
url: https://github.com/yourusername/inscriptiontools

apps:
  - id: inscript-manager
    name: Ordinarinos Inscription Manager
    category: bitcoin
    tagline: Advanced manager for your ordinals and bitcoin node
    icon: https://raw.githubusercontent.com/getumbrel/umbrel-apps/master/bitcoin/icon.svg
    version: "1.0.0"
    port: 3000
    description: A powerful tool to create, view, and manage Bitcoin inscriptions on your Umbrel node. Inscribe Images, 3D files, Rare Sats, Bitmap, BRC-20, Recursive, and SNS names. 