version: "3.7"

services:
  web:
    build:
      context: ./web
    image: ${APP_IMAGE:-inscript-manager}
    container_name: inscript-manager
    restart: on-failure
    stop_grace_period: 1m
    ports:
      - ${APP_INSCRIPT_MANAGER_PORT:-3000}:3000
    volumes:
      - ${APP_DATA_DIR:-.data}:/data
    environment:
      - BITCOIN_RPC_HOST=${BITCOIN_IP:-10.21.21.8}
      - BITCOIN_RPC_PORT=${BITCOIN_RPC_PORT:-8332}
      - BITCOIN_RPC_USER=${BITCOIN_RPC_USER:-umbrel}
      - BITCOIN_RPC_PASSWORD=${BITCOIN_RPC_PASS:-umbrel}
    networks:
      - inscript-network

networks:
  inscript-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.21.0.0/24 