version: '3.7'

services:
  app_proxy:
    environment:
      APP_HOST: inscript-hello-world_web_1
      APP_PORT: 3000
      PROXY_AUTH_ADD: "false"

  web:
    image: ghcr.io/merlini/inscriptiontools:latest
    restart: on-failure
    stop_grace_period: 1m
    volumes:
      - ${APP_DATA_DIR}/data:/data
    environment:
      BITCOIN_IP: ${BITCOIN_IP}
      BITCOIN_RPC_PORT: ${BITCOIN_RPC_PORT}
      BITCOIN_RPC_USER: ${BITCOIN_RPC_USER}
      BITCOIN_RPC_PASS: ${BITCOIN_RPC_PASS}
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:3000 || exit 1
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s 