version: "3.7"

services:
  web:
    image: nginx:alpine
    restart: on-failure
    stop_grace_period: 1m
    volumes:
      - ${APP_DATA_DIR}/data:/data
      - ${APP_DATA_DIR}/www:/usr/share/nginx/html
    ports:
      - "${APP_PORT}:80"
    environment:
      - APP_HOST=${APP_HIDDEN_SERVICE}
    networks:
      - default

volumes:
  data:
    driver: local

networks:
  default:
    driver: bridge 