version: "3.7"

services:
  web:
    image: nginx:alpine
    restart: on-failure
    stop_grace_period: 1m
    ports:
      - ${APP_SPARKLES_HELLO_WORLD_PORT:-4000}:80
    volumes:
      - ${APP_DATA_DIR}/www:/usr/share/nginx/html
    environment:
      - TZ=UTC 